Feature/69 api port and 68 long action name disappear
planimation/frontend pull request #71
Opened 2020-09-29 03:57 UTC by JamieYuu

Resolves the issue #68 and #69

2020-09-30 08:47 UTC, nirlipo commented
Hi @JamieYuu ,

Can you do the PR from the fork into a new branch?

https://www.loom.com/share/bee84d18117047248c7ed7fc86d60276

Thanks

2020-09-30 08:50 UTC, nirlipo commented on Assets/Plugins/webConfig.jslib
> +        if (window.location.hostname == "localhost") {
Perfect, this will allow to run your local dev environment without needing to change port

2020-09-30 08:52 UTC, nirlipo requested changes
See comment in ScenesCoordinator.cs

2020-09-30 08:52 UTC, nirlipo commented on Assets/Visualiser/Scripts/ScenesCoordinator.cs
> +	    //UnityWebRequest www = UnityWebRequest.Post("https://planning-visualisation-solver.herokuapp.com/upload/pddl", formData);
Can you clean the commented lines? no need to keep them

2020-09-30 14:26 UTC, nirlipo requested changes
This may be from earlier iterations, but for some reason, the tabulation of the code is a bit all over the place. Can you reindent the code? Thanks!

2020-09-30 15:35 UTC, JamieYuu commented
I guess the IDE causes the tabulation issue, my VScode automatically formats the document so I didn't see the issue at the beginning, and then I review the file on GitHub and found the problem.

2020-10-01 00:57 UTC, nirlipo approved these changes
Thanks!

2020-10-01 00:57 UTC, merged